<?php
// Add this at the top of your acf-fields.php file
add_action('acf/init', 'register_pool_fence_fields');

function register_pool_fence_fields() {
    if (function_exists('acf_add_local_field_group')):

        acf_add_local_field_group(array(
            'key' => 'group_pool_fence_metadata',
            'title' => 'Pool Fence Metadata',
            'fields' => array(
                array(
                    'key' => 'field_border_color',
                    'label' => 'Border Color',
                    'name' => 'border_color',
                    'type' => 'select',
                    'choices' => array(
                        'Black' => 'Black',
                        'Brown' => 'Brown',
                        'Tan' => 'Tan',
                        'White' => 'White',
                    ),
                    'default_value' => '',
                    'allow_null' => 1,
                    'multiple' => 0,
                    'return_format' => 'value',
                    'placeholder' => 'Select Border Color',
                ),
                array(
                    'key' => 'field_mesh_color',
                    'label' => 'Mesh Color',
                    'name' => 'mesh_color',
                    'type' => 'select',
                    'choices' => array(
                        'Black' => 'Black',
                        'Brown' => 'Brown',
                        'White' => 'White',
                    ),
                    'default_value' => '',
                    'allow_null' => 1,
                    'multiple' => 0,
                    'return_format' => 'value',
                    'placeholder' => 'Select Mesh Color',
                ),
                array(
                    'key' => 'field_pole_color',
                    'label' => 'Pole Color',
                    'name' => 'pole_color',
                    'type' => 'select',
                    'choices' => array(
                        'Black' => 'Black',
                        'Brown' => 'Brown',
                        'Copper Vein' => 'Copper Vein',
                        'Tan' => 'Tan',
                        'White' => 'White',
                    ),
                    'default_value' => '',
                    'allow_null' => 1,
                    'multiple' => 0,
                    'return_format' => 'value',
                    'placeholder' => 'Select Pole Color',
                ),
                array(
                    'key' => 'field_fence_height',
                    'label' => 'Fence Height',
                    'name' => 'fence_height',
                    'type' => 'select',
                    'choices' => array(
                        '3.5 feet' => '3.5 feet',
                        '4 feet' => '4 feet',
                        '5 feet' => '5 feet',
                        'Pet Fence' => 'Pet Fence',
                    ),
                    'default_value' => '',
                    'allow_null' => 1,
                    'multiple' => 0,
                    'return_format' => 'value',
                    'placeholder' => 'Select Fence Height',
                ),
                array(
                    'key' => 'field_fence_layout',
                    'label' => 'Fence Layout',
                    'name' => 'fence_layout',
                    'type' => 'select',
                    'choices' => array(
                        'Complete' => 'Complete',
                        'Partial' => 'Partial',
                    ),
                    'default_value' => '',
                    'allow_null' => 1,
                    'multiple' => 0,
                    'return_format' => 'value',
                    'placeholder' => 'Select Fence Layout',
                ),
                array(
                    'key' => 'field_gate',
                    'label' => 'Gate Type',
                    'name' => 'gate',
                    'type' => 'select',
                    'choices' => array(
                        'Arched' => 'Arched',
                        'Flat' => 'Flat',
                        'None' => 'None',
                    ),
                    'default_value' => '',
                    'allow_null' => 1,
                    'multiple' => 0,
                    'return_format' => 'value',
                    'placeholder' => 'Select Gate Type',
                ),
                array(
                    'key' => 'field_pool_shape',
                    'label' => 'Pool Shape',
                    'name' => 'pool_shape',
                    'type' => 'select',
                    'choices' => array(
                        '90-degree turns' => '90-degree turns',
                        'Above Ground' => 'Above Ground',
                        'Freeform' => 'Freeform',
                        'Ginormous' => 'Ginormous',
                        'Kidney' => 'Kidney',
                        'Oval' => 'Oval',
                        'Rectangle' => 'Rectangle',
                    ),
                    'default_value' => '',
                    'allow_null' => 1,
                    'multiple' => 0,
                    'return_format' => 'value',
                    'placeholder' => 'Select Pool Shape',
                ),
                array(
                    'key' => 'field_surface',
                    'label' => 'Surface Type',
                    'name' => 'surface',
                    'type' => 'select',
                    'choices' => array(
                        'Bricks' => 'Bricks',
                        'Chattahoochee' => 'Chattahoochee',
                        'Concrete' => 'Concrete',
                        'Earth' => 'Earth',
                        'Natural Stone' => 'Natural Stone',
                        'Pavers' => 'Pavers',
                        'Tile' => 'Tile',
                        'Travertine' => 'Travertine',
                        'Artificial Turf' => 'Artificial Turf',
                        'Wood/Composite Deck' => 'Wood/Composite Deck',
                    ),
                    'default_value' => '',
                    'allow_null' => 1,
                    'multiple' => 0,
                    'return_format' => 'value',
                    'placeholder' => 'Select Surface Type',
                ),
                array(
                    'key' => 'field_upgrades',
                    'label' => 'Upgrades',
                    'name' => 'upgrades',
                    'type' => 'checkbox',
                    'choices' => array(
                        'Alarm' => 'Alarm',
                        'Ground Solar Lights' => 'Ground Solar Lights',
                        'Top Pole Solar Lights' => 'Top Pole Solar Lights',
                        'Volleyball Net' => 'Volleyball Net',
                    ),
                    'default_value' => array(),
                    'allow_custom' => 0,
                    'layout' => 'vertical',
                    'toggle' => 1,
                    'return_format' => 'value',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'attachment',
                        'operator' => '==',
                        'value' => 'all',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ));

    endif;
}